version: "2"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  server:
    build: ./server
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - mongodb
    command: npm run start
  client:
    build: ./client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
    links:
      - server
    depends_on:
      - server
    command: npm run start
