export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_GOOGLE_REQUEST = "LOGIN_GOOGLE_REQUEST";
export const LOGIN_FACEBOOK_REQUEST = "LOGIN_FACEBOOK_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SUCCESS_ALERT = "SUCCESS_ALERT";
export const WARNING_ALERT = "WARNING_ALERT";
export const ERROR_ALERT = "ERROR_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
