// Product actions
export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCEED = 'FETCH_TRANSACTIONS_SUCCEED';
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCEED = 'DELETE_PRODUCT_SUCCEED';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCEED = 'CREATE_PRODUCT_SUCCEED';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';

export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const EDIT_PRODUCT_SUCCEED = 'EDIT_PRODUCT_SUCCEED';
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED';

// User actions
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCEED = 'FETCH_USERS_SUCCEED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
// export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const PRODUCT_DETAIL_PAGE_LOADED = 'PRODUCT_DETAIL_PAGE_LOADED';
export const PRODUCT_DETAIL_PAGE_LOADING = 'PRODUCT_DETAIL_PAGE_LOADING';
export const PRODUCT_DETAIL_PAGE_ERRORED = 'PRODUCT_DETAIL_PAGE_ERRORED';
