export const LOGIN_PAGE_LOADED = "LOGIN_PAGE_LOADED";
export const LOGIN_PAGE_LOADING = "LOGIN_PAGE_LOADING";
export const LOGIN_PAGE_FAILED = "LOGIN_PAGE_FAILED";

export const REGISTER_PAGE_LOADED = "REGISTER_PAGE_LOADED";
export const REGISTER_PAGE_LOADING = "REGISTER_PAGE_LOADING";
export const REGISTER_PAGE_FAILED = "REGISTER_PAGE_FAILED";
