export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const WARNING_ALERT = 'WARNING_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
