export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const REQUEST_PROFILE_SUCCESS = 'REQUEST_PROFILE_SUCCESS';
export const REQUEST_PROFILE_FAILURE = 'REQUEST_PROFILE_FAILURE';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
 